server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://prod-db:5432/userdb
    username: user_prod
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
