server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://preprod-db:5432/userdb
    username: user_preprod
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
